version: '3.8'

services:

  ############################################
  #               MQTT Broker                #
  ############################################
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./volumes/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - iot-net

  ############################################
  #               Zookeeper                  #
  ############################################
  zookeeper:
    image: bitnami/zookeeper:3.7.1
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./volumes/zookeeper:/bitnami
    networks:
      - iot-net

  ############################################
  #                 Kafka                    #
  ############################################
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - iot-net

  ############################################
  #              Spark Master                #
  ############################################
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"   # Port Spark master
      - "8080:8080"   # UI Spark master
    volumes:
      - ./spark:/app
    networks:
      - iot-net

  ############################################
  #                 MinIO                    #
  ############################################
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9000:9000     # API
      - 9001:9001     # Console Web
    volumes:
      - minio_data:/data
    networks:
      - iot-net

  ############################################
  #              TimescaleDB                 #
  ############################################
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: iotdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - iot-net

  ############################################
  #                Grafana                   #
  ############################################
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - iot-net

############################################
#          Réseaux & Volumes               #
############################################
networks:
  iot-net:

volumes:
  pgdata:
  minio_data:
  grafana_data:
